<?php

namespace App\Controller\EasyAdmin;

use App\EasyAdmin\VotesField;
use App\Entity\Question;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\Field;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;

class QuestionCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Question::class;
    }

    public function configureFields(string $pageName): iterable
    {
		yield IdField::new('id')
			->onlyOnIndex();
		yield Field::new('name');
		yield Field::new('slug')
			->hideOnIndex()
			->setFormTypeOption(
				'disabled',
				$pageName !== Crud::PAGE_NEW
			);
	    yield AssociationField::new('topic');
		yield TextareaField::new('question')
			->hideOnIndex()
			->setFormTypeOptions([
				'row_attr' => [
					'data-controller' => 'snarkdown',
				],
				'attr' => [
					'data-snarkdown-target' => 'input',
					'data-action' => 'snarkdown#render',
				],
			])
			->setHelp('Podgląd:');
	    yield AssociationField::new('askedBy')
		    ->autocomplete()
	        ->formatValue(static function($value, Question $question) { //value to wartośc pola, a $question to obiekt question obecny
				if (!$user = $question->getAskedBy()) { //sprawdza czy zmienna user istnieje i czy sa zwraca coś getAskedBy()
					return null;
				}

				return sprintf('%s&nbsp;(%s)', $user->getEmail(), $user->getQuestions()->count());

	        })
		    ->setQueryBuilder(function (QueryBuilder $queryBuilder) {//tutaj tylko modyfikiujemy queryBuildera więc nie potrzebujemy nic zwracać
				$queryBuilder->andWhere('entity.enabled = :enabled')
					->setParameter('enabled', 1);
		    });
	    yield VotesField::new('votes','Total Votes')
	        ->setTextAlign('right');
		yield AssociationField::new('answers')//orphant removal trzeba dołożyć, żeby nie było pytań bez autora :)
			->autocomplete()
			//jak jest autoicomplete to 'choice_label nie działa'
			//->setFormTypeOption('choice_label', 'id')//tutaj wybieramy z które pole encji chcemy wybrać
			->setFormTypeOption('by_reference', false);//musi byc, żeby sięzapisało
	    yield Field::new('createAt')
	        ->hideOnForm();
    }

	public function configureCrud(Crud $crud): Crud
	{
		return parent::configureCrud($crud)
			->setDefaultSort([
				'askedBy.enabled' => 'DESC',
				'createdAt' => 'DESC',
			]); // TODO: Change the autogenerated stub
	}


}
