<?php

namespace App\Controller\EasyAdmin;

use App\Entity\Topic;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class TopicCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Topic::class;
    }

    /*
    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id'),
            TextField::new('title'),
            TextEditorField::new('description'),
        ];
    }
    */
	public function configureCrud(Crud $crud): Crud
	{
		return parent::configureCrud($crud)
			->showEntityActionsInlined(); // TODO: Change the autogenerated stub
	}

	public function configureActions(Actions $actions): Actions
	{
		return parent::configureActions($actions)
			->disable(Action::DETAIL); // TODO: Change the autogenerated stub
	}


}
